// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreParsers.Infrastructure;

namespace StoreParsers.Migrations.GooglePlayAppsRepositoryMigrations
{
    [DbContext(typeof(GooglePlayAppsRepository))]
    [Migration("20190618202553_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("StoreParsers.Domain.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Icon");

                    b.Property<string>("Name");

                    b.Property<double>("Rating");

                    b.Property<int>("SearchRequestId");

                    b.HasKey("ApplicationId");

                    b.HasIndex("SearchRequestId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("StoreParsers.Domain.Screenshot", b =>
                {
                    b.Property<int>("ScreenshotId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ApplicationId");

                    b.Property<string>("Url");

                    b.HasKey("ScreenshotId");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Screenshots");
                });

            modelBuilder.Entity("StoreParsers.Domain.SearchRequest", b =>
                {
                    b.Property<int>("SearchRequestId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Keyword");

                    b.HasKey("SearchRequestId");

                    b.ToTable("SearchRequests");
                });

            modelBuilder.Entity("StoreParsers.Domain.Application", b =>
                {
                    b.HasOne("StoreParsers.Domain.SearchRequest", "SearchRequest")
                        .WithMany("Applications")
                        .HasForeignKey("SearchRequestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StoreParsers.Domain.Screenshot", b =>
                {
                    b.HasOne("StoreParsers.Domain.Application", "Application")
                        .WithMany("Screenshots")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
